//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom4_QLST.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class GiaoDich
    {
        public int MaGiaoDich { get; set; }
        public Nullable<int> MaKhachHang { get; set; }
        public Nullable<int> MaSanPham { get; set; }
        public Nullable<int> MaNhanVien { get; set; }
        public Nullable<int> SoLuong { get; set; }

        public Nullable<System.DateTime> NgayGiaoDich { get; set; }
        [DisplayFormat(DataFormatString = "{0:N0} VNĐ")]
        public Nullable<decimal> TongTien { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
